rm(list = ls())

library(manifestoR)
library(quanteda)
library(tm)
library(readtext)
library(corpus)
library(googleLanguageR)

gl_auth("C:/Users/rzava/Box Sync/Tech Saliency/R scripts/GAPI.json")
mp_setapikey("C:/Users/rzava/Box Sync/Tech Saliency/R scripts/MPkey.txt")


DE_corp <- mp_corpus(countryname == "Germany" & date >= 200000)
CZ_corp <- mp_corpus(countryname == "Czech Republic" & date >= 200000)
IC_corp <- mp_corpus(countryname == "Iceland" & date >= 200000)
FR_corp <- mp_corpus(countryname == "France" & date >= 200000)
CN_corp <- mp_corpus(countryname == "Canada" & date >= 200000)
IT_corp <- mp_corpus(countryname == "Italy" & date >= 200000)
LV_corp <- mp_corpus(countryname == "Latvia" & date >= 200000)
NW_corp <- mp_corpus(countryname == "Norway" & date >= 200000)
FI_corp <- mp_corpus(countryname == "Finland" & date >= 200000)
UK_corp <- mp_corpus(countryname == "United Kingdom" & date >= 200000)
AT_corp <- mp_corpus(countryname == "Austria" & date >= 200000)
SZ_corp <- mp_corpus(countryname == "Switzerland" & date >= 200000)
PL_corp <- mp_corpus(countryname == "Poland" & date >= 200000)
SW_corp <- mp_corpus(countryname == "Sweden" & date >= 200000)
LX_corp <- mp_corpus(countryname == "Luxembourg" & date >= 200000)
ET_corp <- mp_corpus(countryname == "Estonia" & date >= 200000)
BG_corp <- mp_corpus(countryname == "Belgium" & date >= 200000)

writeCorpus(DE_corp,"C:/Users/rzava/Box Sync/Tech Saliency/Corpora/DE")
writeCorpus(CZ_corp,"C:/Users/rzava/Box Sync/Tech Saliency/Corpora/CZ")
writeCorpus(IC_corp,"C:/Users/rzava/Box Sync/Tech Saliency/Corpora/IC")
writeCorpus(FR_corp,"C:/Users/rzava/Box Sync/Tech Saliency/Corpora/FR")
writeCorpus(CN_corp,"C:/Users/rzava/Box Sync/Tech Saliency/Corpora/CN")
writeCorpus(IT_corp,"C:/Users/rzava/Box Sync/Tech Saliency/Corpora/IT")
writeCorpus(LV_corp,"C:/Users/rzava/Box Sync/Tech Saliency/Corpora/LV")
writeCorpus(NW_corp,"C:/Users/rzava/Box Sync/Tech Saliency/Corpora/NW")
writeCorpus(FI_corp,"C:/Users/rzava/Box Sync/Tech Saliency/Corpora/FI")
writeCorpus(UK_corp,"C:/Users/rzava/Box Sync/Tech Saliency/Corpora/UK")
writeCorpus(AT_corp,"C:/Users/rzava/Box Sync/Tech Saliency/Corpora/AT")
writeCorpus(SZ_corp,"C:/Users/rzava/Box Sync/Tech Saliency/Corpora/SZ")
writeCorpus(PL_corp,"C:/Users/rzava/Box Sync/Tech Saliency/Corpora/PL")
writeCorpus(SW_corp,"C:/Users/rzava/Box Sync/Tech Saliency/Corpora/SW")
writeCorpus(LX_corp,"C:/Users/rzava/Box Sync/Tech Saliency/Corpora/LX")
writeCorpus(ET_corp,"C:/Users/rzava/Box Sync/Tech Saliency/Corpora/ET")
writeCorpus(BG_corp,"C:/Users/rzava/Box Sync/Tech Saliency/Corpora/BG")
            
## NOW MANUALLY ADD PIRATE DOCUMENTS TO FOLDERS ##     